+function(){
	//找到元素
	username=document.getElementsByName("username")[0];
	phone=document.getElementsByName("phonenumber")[0];
	reset=document.getElementsByName("reset")[0];
	username.onfocus=getFocus;
	phone.onfocus=getFocus1;
	function getFocus(){
		//为input穿txt_focus
		this.className="txt_focus";
		if(this.value=="请输入您的姓名"){
			this.value="";//清除当前文本框的内容
		}
		//找到input旁边的span
		this.nextElementSibling.className="tishi";
	};
	function getFocus1(){
		//为input穿txt_focus
		this.className="txt_focus";
		if(this.value=="请输入您的电话号码"){
			this.value="";//清除当前文本框的内容
		}
		//找到input旁边的span
		this.nextElementSibling.className="tishi";
	};
	//为username绑定失去焦点事件:
	username.onblur=function(){
		if(this.value==""){
			this.className="hintText";
			this.value="请输入您的姓名";
			this.nextElementSibling.className="vali_Info";
		}
		else
			vali(this,/^\w{1,10}$/);//调动vali
	}
	function vali(txt,reg){
		txt.className="";//清除当前文本框的class		
		//找到input旁边的span
		var span=txt.nextElementSibling
		//用正则验证txt的内容，通过
		if(reg.test(txt.value))
			//为span穿vali_success
			span.className="vali_success";
		else//否则
			span.className="vali_fail";//为span穿vali_fail
	}
	//为phonenumber绑定失去焦点事件
	phone.onblur=function(){
		if(this.value==""){
			this.className="hintText";
			this.value="请输入您的电话号码";
			this.nextElementSibling.className="vali_Info";
		}else
			vali(this,/^((\+86|0086)?\s*1[34578]\d{9})$/);//调动vali
	}
	//为content绑定获得焦点事件
	content=document.getElementsByName("content")[0];
	content.onfocus=function(){
		this.className="normalText";
		if(this.value=="请输入留言内容"){
			this.value="";//清除当前文本框的内容
		}
	}
	content.onblur=function(){
		this.className="normalText";
		if(this.value==""){
			this.value="请输入留言内容";
			this.className="hintText";
		}
	}
	//为reset绑定点击事件
	reset.onclick=function(){
		username.nextElementSibling.className="vali_Info";
		phone.nextElementSibling.className="vali_Info";
		username.className="hintText";
		phone.className="hintText";
	}
}();